(function(){
  'use strict';
  const workSets=[
    ['assets/work-01.jpg','assets/work-02.jpg','assets/work-03.jpg','assets/work-04.jpg','assets/work-05.jpg','assets/work-06.jpg'],
    ['assets/work-04.jpg','assets/work-05.jpg','assets/work-06.jpg','assets/work-07.jpg','assets/work-08.jpg','assets/work-09.jpg'],
    ['assets/work-07.jpg','assets/work-08.jpg','assets/work-09.jpg','assets/work-10.jpg','assets/work-11.jpg','assets/work-12.jpg'],
    ['assets/work-10.jpg','assets/work-11.jpg','assets/work-12.jpg','assets/work-13.jpg','assets/work-14.jpg','assets/work-01.jpg'],
    ['assets/work-13.jpg','assets/work-14.jpg','assets/work-01.jpg','assets/work-02.jpg','assets/work-03.jpg','assets/work-04.jpg'],
    ['assets/work-02.jpg','assets/work-03.jpg','assets/work-04.jpg','assets/work-05.jpg','assets/work-06.jpg','assets/work-07.jpg'],
    ['assets/work-05.jpg','assets/work-06.jpg','assets/work-07.jpg','assets/work-08.jpg','assets/work-09.jpg','assets/work-10.jpg'],
    ['assets/work-08.jpg','assets/work-09.jpg','assets/work-10.jpg','assets/work-11.jpg','assets/work-12.jpg','assets/work-13.jpg'],
    ['assets/work-11.jpg','assets/work-12.jpg','assets/work-13.jpg','assets/work-14.jpg','assets/work-01.jpg','assets/work-02.jpg'],
    ['assets/work-14.jpg','assets/work-01.jpg','assets/work-02.jpg','assets/work-03.jpg','assets/work-04.jpg','assets/work-05.jpg'],
    ['assets/work-03.jpg','assets/work-04.jpg','assets/work-05.jpg','assets/work-06.jpg','assets/work-07.jpg','assets/work-08.jpg']
  ];
  const masters=[
    {name:'Tunuk Nails',cat:'nails',district:'Vefa Center · Байтик Баатыра 98',walk:'на месте',price:'1400 сом',rating:0,reviewsCount:0,isCatalog:true,experience:'Опыт 5 лет',saves:142,emoji:'💅',avatar:'assets/tunuk-new.png',desc:'Аккуратное покрытие, френч и нежные дизайны. Подходит тем, кто любит clean girl nails.',ig:'tunuk_nails',lat:42.857255,lng:74.609848,bookingDays:60,services:[{name:'Френч с дизайном',desc:'Нежный френч с цветами',price:'1500 сом',time:'2 ч.'},{name:'Омбре',desc:'Плавный переход цветов',price:'1300 сом',time:'2 ч.'},{name:'Наращивание',desc:'Классическое наращивание',price:'1700 сом',time:'2,5 ч.'},{name:'Маникюр + покрытие',desc:'Покрытие в один тон',price:'900 сом',time:'1,5 ч.'},{name:'Дизайн ногтей',desc:'Дизайн на выбор',price:'1200 сом',time:'1,5 ч.'}]},
    {name:'Adel Beauty',cat:'nails',district:'Нижний Джал',walk:'на месте',price:'1200 сом',rating:0,reviewsCount:0,isCatalog:true,experience:'Опыт 4 года',saves:96,emoji:'🎀',avatar:'assets/adel-new.png',desc:'Маникюр, укрепление и дизайны на каждый день. Мягкий розовый стиль и аккуратная форма.',ig:'adel_nails',lat:42.842427,lng:74.566250,bookingDays:45,services:[{name:'Маникюр',desc:'Обработка и покрытие',price:'1200 сом',time:'1,5 ч.'},{name:'Укрепление',desc:'Укрепление гелем',price:'1500 сом',time:'2 ч.'},{name:'Френч',desc:'Классический френч',price:'1400 сом',time:'2 ч.'},{name:'Дизайн',desc:'Дизайн на выбор',price:'1600 сом',time:'2 ч.'},{name:'Снятие + маникюр',desc:'Полный комплекс',price:'1300 сом',time:'2 ч.'}]},
    {name:'Alya Lashes',cat:'lashes',district:'5 микрорайон, дом 2',walk:'на месте',price:'1000 сом',rating:0,reviewsCount:0,isCatalog:true,experience:'Опыт 6 лет',saves:83,emoji:'👁️',avatar:'assets/alya-new.png',desc:'Наращивание ресниц: натуральный эффект, лисий эффект, мокрый эффект.',ig:'alya_lashes',lat:42.873765,lng:74.636127,bookingDays:31,services:[{name:'Наращивание ресниц',desc:'Натуральный эффект',price:'1000 сом',time:'2 ч.'}]},
    {name:'Mira Brows',cat:'brows',district:'Asia Mall · Ч. Айтматова 3',walk:'на месте',price:'700 сом',rating:0,reviewsCount:0,isCatalog:true,experience:'Опыт 3 года',saves:74,emoji:'🤎',avatar:'assets/mira-new.png',desc:'Коррекция, окрашивание и долговременная укладка бровей.',ig:'mira_brows',lat:42.855421,lng:74.586573,bookingDays:90,services:[{name:'Коррекция бровей',desc:'Форма и окрашивание',price:'700 сом',time:'1 ч.'}]},
    {name:'Nursaule Nails',cat:'nails',district:'Asia Mall',walk:'на месте',price:'900 сом',rating:0,reviewsCount:0,isCatalog:true,experience:'Опыт 4 года',saves:68,emoji:'💅',avatar:'assets/nursaule-new.png',desc:'Маникюр и длинный овал. Аккуратные формы и современные дизайны.',ig:'nursaule_nails',lat:42.85575,lng:74.58710,bookingDays:31,services:[{name:'Маникюр + покрытие',desc:'Однотонное покрытие',price:'900 сом',time:'1,5 ч.'}]},
    {name:'Diana Nail Art',cat:'nails',district:'Токтоналиева 52 · Политех',walk:'на месте',price:'1500 сом',rating:0,reviewsCount:0,isCatalog:true,experience:'Опыт 5 лет',saves:121,emoji:'🎨',avatar:'assets/diana-new.png',desc:'Ручная роспись и сложные дизайны ногтей.',ig:'diana_nail_art',lat:42.84975,lng:74.57865,bookingDays:31,services:[{name:'Маникюр со сложным дизайном',desc:'Ручная роспись',price:'1500 сом',time:'2,5 ч.'}]},
    {name:'Valeria Nails',cat:'nails',district:'Аламедин Grand · Курманджан Датка 226',walk:'на месте',price:'1000 сом',rating:0,reviewsCount:0,isCatalog:true,experience:'Опыт 5 лет',saves:89,emoji:'🤍',avatar:'assets/valeria-new.png',desc:'Френч и аккуратный повседневный маникюр.',ig:'valeria_nails',lat:42.88535,lng:74.63740,bookingDays:31,services:[{name:'Френч',desc:'Классический или цветной',price:'1000 сом',time:'2 ч.'}]},
    {name:'Marina Nails',cat:'nails',district:'Район Карла Маркса',walk:'на месте',price:'1000 сом',rating:0,reviewsCount:0,isCatalog:true,experience:'Опыт 8 лет',saves:103,emoji:'✨',avatar:'assets/marina-new.png',desc:'Маникюр и покрытие с вниманием к деталям.',ig:'marina_nails',lat:42.87480,lng:74.63080,bookingDays:31,services:[{name:'Маникюр + покрытие',desc:'Полный комплекс',price:'1000 сом',time:'1,5 ч.'}]},
    {name:'Nina Nails',cat:'nails',district:'5 микрорайон, дом 2 · салон «Алия»',walk:'на месте',price:'1000 сом',rating:0,reviewsCount:0,isCatalog:true,experience:'Опыт 11 лет',saves:156,emoji:'🌸',avatar:'assets/nina-new.png',desc:'Качественный и аккуратный маникюр с большим опытом работы.',ig:'nina_nails',lat:42.87370,lng:74.63605,bookingDays:31,services:[{name:'Маникюр',desc:'Обработка и однотонное покрытие',price:'1000 сом',time:'1,5 ч.'}]},
    {name:'Nellinails Studio',cat:'nails',district:'Куйбышева 93 · ЦУМ / Дордой Плаза',walk:'на месте',price:'1000 сом',rating:0,reviewsCount:0,isCatalog:true,experience:'Студия маникюра',saves:134,emoji:'💗',avatar:'assets/nellinails-new.png',desc:'Маникюр, педикюр и услуга в 4 руки за 1 час 30 минут.',ig:'nellinails_studio',lat:42.87725,lng:74.61475,bookingDays:31,services:[{name:'Маникюр однотонный',desc:'Однотонное покрытие',price:'1000 сом',time:'1,5 ч.'},{name:'Педикюр однотонный',desc:'Педикюр с покрытием',price:'1200 сом',time:'1,5 ч.'}]},
    {name:'Bogdan Nails',cat:'nails',district:'Бишкек · принимает на дому',walk:'на месте',price:'1700 сом',rating:0,reviewsCount:0,isCatalog:true,experience:'Индивидуальная запись',saves:61,emoji:'🖤',avatar:'assets/bogdan-new.png',desc:'Фиксированная стоимость с ремонтом, дизайном и массажем рук.',ig:'bogdan_nails',lat:42.86650,lng:74.59830,bookingDays:31,services:[{name:'Маникюр полный комплекс',desc:'Ремонт, дизайн и массаж рук включены',price:'1700 сом',time:'3 ч.'}]}
  ];
  masters.forEach((m,i)=>{m.id=i;m.gallery=[...(workSets[i]||workSets[0])];});
  window.PN_MASTER_WORK_SETS=workSets;
  window.PN_MASTERS=masters;
  window.PNCloneMasters=()=>masters.map(m=>({...m,gallery:[...(m.gallery||[])],services:(m.services||[]).map(s=>({...s}))}));
})();
